### ISSUE TITLE
Magento 2 Compatibily

### ISSUE THREAD

**Issue by Bobspadger** [bernieke/python-magento#3]
Discussion rather than issue:

Do we want to put any effort or thought into adding in magento2 compatibility or for that matter Rest / Soap compatibility ?

If we were to build in Rest Capability to this now, we would be putting the ground work in for the magento 2 release ?

Thoughts ?

Alex

**Comment by bernieke** [comment]
I don't really see the point. Neither implementation would be anything like the xmlrpc implementation (or each other for that matter.) So at most you'd have a generic interface. And since neither rest (which is incomplete to boot, at least in magento1), nor soap is auto-discovering so far as I know, even that would just be a meaningless hack...

I'd rather propose to start a second project python-magento2 instead. If none of the already existing python magento rest or soap projects are good enough that is...

Or if a generic interface is really what you're after, you could implement that as a separate project, and allow it to use python-magento and other rest/soap projects as its backends.
